FROM alpine:latest

RUN apk add --update --no-cache docker python3 py3-pip bash

RUN pip3 install --upgrade \
    pip python-dateutil requests Pillow \
    sphinx sphinx-gallery sphinx_rtd_theme \
    sphinx-panels sphinxcontrib-bibtex sphinx-design
